alias gitt="git clone"
alias jup="cd && cd d:/Jupyter && jupyter lab"
export PATH="$PATH:$HOME/scripts"
alias gad="git_auto_deploy.sh"
alias gup="./update_repo.sh"
alias gco="./commit_script.sh"
alias readkey="./my.sh"
alias nvbash="nvim  ~/.bashrc"
alias nabash="nano ~/.bashrc"
alias sobash="source  ~/.bashrc"
alias py="python3=py"
alias servor="npx servor ./dist"
alias goo=" cd G:/'My Drive' "
